# Generated by Django 5.2.7 on 2025-11-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=20)),
                ('arroba', models.FloatField()),
                ('estado', models.CharField(max_length=2)),
                ('regiao', models.CharField(max_length=20)),
            ],
        ),
    ]
