# Generated by Django 5.2.7 on 2025-12-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boi',
            name='date',
            field=models.DateField(default='2025-12-01'),
            preserve_default=False,
        ),
    ]
