# Generated by Django 5.2.7 on 2025-12-01 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0002_boi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
    ]
