# Generated by Django 5.2.7 on 2025-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0003_alter_boi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='date',
            field=models.DateTimeField(default='2026-01-01'),
        ),
    ]
