# Generated by Django 5.2.7 on 2025-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0004_alter_boi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='date',
            field=models.DateField(default='2026-01-01'),
        ),
    ]
