# Generated by Django 5.2.7 on 2025-12-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0005_alter_boi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
