# Generated by Django 5.2.7 on 2026-01-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0006_alter_boi_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='SP', max_length=2)),
                ('regiao', models.CharField(default='oeste', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default='2026-01-01')),
                ('nome', models.CharField(default='boi gordo', max_length=20)),
                ('idade', models.IntegerField(default='36')),
                ('arroba', models.FloatField(default='300')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='boiAPI.estado')),
            ],
        ),
    ]
