# Generated by Django 5.2.7 on 2026-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0007_estado_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='arroba',
            field=models.FloatField(default=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(default=36),
        ),
    ]
