# Generated by Django 5.2.7 on 2026-01-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0008_alter_animal_arroba_alter_animal_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(default='SP', max_length=25),
        ),
    ]
