# Generated by Django 6.0.2 on 2026-02-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0009_alter_estado_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boi_gordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='', max_length=50)),
                ('animal', models.CharField(default='boi gordo', max_length=50)),
                ('regiao', models.CharField(default='', max_length=50)),
                ('arroba_a_vista', models.CharField(default='', max_length=10)),
                ('arroba_a_prazo', models.CharField(default='', max_length=10)),
                ('variacao', models.CharField(default='0,0', max_length=10)),
                ('data', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='boi',
        ),
    ]
