# Generated by Django 6.0.2 on 2026-02-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0010_boi_gordo_delete_boi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_reposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='', max_length=50)),
                ('animal', models.CharField(default='boi gordo', max_length=50)),
                ('valor_animal', models.CharField(default='', max_length=50)),
                ('relacao_troca_1', models.CharField(max_length=10)),
                ('relacao_troca_2', models.CharField(max_length=10)),
                ('data', models.DateField()),
            ],
        ),
    ]
