# Generated by Django 6.0.2 on 2026-02-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0011_animal_reposicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi_gordo',
            name='arroba_a_prazo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='boi_gordo',
            name='arroba_a_vista',
            field=models.CharField(max_length=10),
        ),
    ]
