# Generated by Django 6.0.2 on 2026-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiAPI', '0012_alter_boi_gordo_arroba_a_prazo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_reposicao',
            old_name='relacao_troca_1',
            new_name='relacao_troca',
        ),
        migrations.RenameField(
            model_name='animal_reposicao',
            old_name='relacao_troca_2',
            new_name='valor_kg',
        ),
        migrations.AlterField(
            model_name='boi_gordo',
            name='regiao',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
